### ISSUE TITLE
Support for Orion to support 2+ clients (especially for inference workloads)

### ISSUE THREAD

**Issue by aravindhank11** [eth-easl/orion#25]
As discussed in https://github.com/eth-easl/orion/issues/24, opening this issue to track Orion's ability to handle multiple clients.

**Comment by fotstrt** [comment]
@aravindhank11 I am closing this issue after merging some fixes for multi-client setups. 
The mult-client configuration files are structured similarly to the 2-client ones (i.e. the high-priority job is the last one in the configuration file). I added an example [here](https://github.com/eth-easl/orion/blob/main/benchmarking/multi_client_example.json).

**Comment by aravindhank11** [comment]
Thank you!
