### ISSUE TITLE
Question about measuring Compute throughput utilization

### ISSUE THREAD

**Issue by atomicapple0** [eth-easl/orion#34]
Hi,

How were the plots of `GPU Compute Throughput Utilization` and `GPU Memory Bandwidth Utilization` in figures 1,8,9 in the paper generated? Were these metrics recorded with Nsight Compute, Cupti, Nvml, or through some different api? Can this script be shared if possible?

Best,
Brian

**Comment by fotstrt** [comment]
Hi Brian,

We used a combination of the Nsight Systems and Nsight Compute tools.
More specifically, we took the trace of execution from Nsight Systems (i.e. start and end of each kernel) and for each kernel, its compute/memory utilization via Nsight Compute.

All scripts that we used are available in [https://github.com/eth-easl/orion/tree/main/profiling](https://github.com/eth-easl/orion/tree/main/profiling)

Instructions on how to use the scripts are in [https://github.com/eth-easl/orion/blob/main/PROFILE.md](https://github.com/eth-easl/orion/blob/main/PROFILE.md).
For generating the plots, after you need all steps up to this: [https://github.com/eth-easl/orion/blob/main/PROFILE.md#optional-plot-traces](https://github.com/eth-easl/orion/blob/main/PROFILE.md#optional-plot-traces)


I hope that helps!

**Comment by atomicapple0** [comment]
Thank you! This is very helpful. :D
