### ISSUE TITLE
In the example provided, the Memory_footprint values are all set to 0. Could you clarify why this is the case?

### ISSUE THREAD

**Issue by tjujingzong** [eth-easl/orion#36]
![image](https://github.com/user-attachments/assets/f46864f1-0cbf-4a38-879a-514b836ccea2)

**Comment by fotstrt** [comment]
Hi! Thank you for your question! 

We do not use the Memory_footprint value anywhere, so its value does not matter. I will try to clean it up to avoid confusion. The entries that we are using are: 

- Profile: 0/1 (shows if kernel is compute or memory heavy)
- SM_Usage: the percentages of SMs being used
- Duration: the duration of the kernel (in ns)

I hope that helps.

**Comment by tjujingzong** [comment]
> Hi! Thank you for your question!
> 
> We do not use the Memory_footprint value anywhere, so its value does not matter. I will try to clean it up to avoid confusion. The entries that we are using are:
> 
> * Profile: 0/1 (shows if kernel is compute or memory heavy)
> * SM_Usage: the percentages of SMs being used
> * Duration: the duration of the kernel (in ns)
> 
> I hope that helps.

Thank you for your time and assistance!
